"use client"

import { ChakraProvider, defaultSystem } from "@chakra-ui/react"
import {
  ColorModeProvider,
  type ColorModeProviderProps,
} from "@/components/chakra-ui/color-mode"

/**
 * Chakra UI Provider generated by Chakra CLI
 * can be used for configuring themes and other config
 */
export function ChakraUIProvider(props: ColorModeProviderProps) {
  return (
    <ChakraProvider value={defaultSystem}>
      <ColorModeProvider {...props} />
    </ChakraProvider>
  )
}
